package com.drools_space.call_rest_api;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CallRestApi implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CallRestApi() {
    }




}