package com.drools_space.call_rest_api;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CallRestApi implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.String status;

	public CallRestApi() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public CallRestApi(java.lang.String type, java.lang.String status) {
		this.type = type;
		this.status = status;
	}

}